# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='submit_time',
        ),
        migrations.RemoveField(
            model_name='availabletime',
            name='day',
        ),
        migrations.AddField(
            model_name='userphoto',
            name='user_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='user_phone',
            field=models.CharField(default='', max_length=128),
        ),
    ]
