# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160821_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userphoto',
            old_name='image_name',
            new_name='photo_name',
        ),
    ]
