# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160821_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.CharField(default='', max_length=32),
        ),
    ]
