# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160821_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='photo_people_number',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='appointment',
            name='photo_type',
            field=models.CharField(default='', max_length=32),
        ),
    ]
