# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160821_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='user_email',
        ),
        migrations.AddField(
            model_name='appointment',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
